app:
  name: "repo-onboarding-copilot"
  version: "1.0.0-dev"
  debug: true

logging:
  level: "debug"
  format: "json"

security:
  max_url_length: 2048
  allowed_schemes:
    - "http"
    - "https"
    - "git" 
    - "ssh"
  enable_sanitization: true