app:
  name: "repo-onboarding-copilot"
  version: "1.0.0"
  debug: false

logging:
  level: "info"
  format: "json"

security:
  max_url_length: 2048
  allowed_schemes:
    - "https"
    - "git"
    - "ssh"
  enable_sanitization: true